"""campaign progress

Revision ID: 216f25bcaa7c
Revises: e01b2f7bdea8
Create Date: 2024-07-26 23:15:30.913419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216f25bcaa7c'
down_revision = 'e01b2f7bdea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
