""""adreq.requirements modified

Revision ID: beb367d09f4b
Revises: e5013c297e4b
Create Date: 2024-07-30 19:52:31.487678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb367d09f4b'
down_revision = 'e5013c297e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    with op.batch_alter_table('adrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adrequest', schema=None) as batch_op:
        batch_op.drop_column('message')

    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_body', sa.VARCHAR(length=256), nullable=False),
    sa.Column('ad_id', sa.INTEGER(), nullable=True),
    sa.Column('influ_id', sa.INTEGER(), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['adrequest.id'], ),
    sa.ForeignKeyConstraint(['influ_id'], ['influencer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
