""""adreq.requirements modified

Revision ID: e5013c297e4b
Revises: 8c11decff572
Create Date: 2024-07-29 22:57:28.215555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5013c297e4b'
down_revision = '8c11decff572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('camp_id', sa.INTEGER(), nullable=True),
    sa.Column('influ_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['influ_id'], ['influencer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
